version: '3'

services:
  selectel_billing_exporter:
    container_name: selectel_billing_exporter
    build: .
    image: mxssl/selectel_billing_exporter:latest
    ports:
      - "6789:80"
    restart: always
    environment:
      TOKEN: селектел_api_токен
